# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 82efc3cc522fd5469848e7f96ee5508af2e1c1a8663b20dcfb9e22c12e013552f979239108bec1d53c27a0c0db9e0722c2f4353fe0be3f8fee152afdb5b6249a

test:
  secret_key_base: 56c2ba41a4a70b66ca4f4d00e94870132cdd65a0f36bf239770bf68705c238a1dc753c904279f42361e378af0b62ce4654d4baec4f11bac8ccdccab2a4052f04

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
